### ISSUE TITLE
右上のオプションにこのGitHubリポジトリへのリンクを追加する

### ISSUE THREAD

**Issue by Atria64** [Atria64/SmartController#26]
「GitHubリポジトリ」というテキストで追加したい。

## 「やってやるよ」という優しい方
コメントをくだされば喜んでアサインします。
`develop`ブランチから新しく`feature`ブランチを生やして作業をお願いします。

**Comment by Atria64** [comment]
# スクリーンショット
![Screenshot_20210208-041352](https://user-images.githubusercontent.com/49768768/107156863-1dd5f600-69c4-11eb-9416-d9ebf696d144.png)

**Comment by AconCavy** [comment]
こんにちは。
こちらのIssueやってもよろしいでしょうか。

**Comment by Atria64** [comment]
@AconCavy ぜひお願いします!
わからないことがあれば言っていただければ!

**Comment by AconCavy** [comment]
ありがとうございます。

端末の言語設定が日本語の場合は「GitHubリポジトリ」、英語の場合は「GitHub Repository」のように表記を変えることもできますが、日本語決め打ちのほうがいいですか?

**Comment by Atria64** [comment]
現在多言語対応は考えてないので、日本語決め打ちでオッケーです!

**Comment by AconCavy** [comment]
PR送りました。
もし意図と異なる箇所があれば教えてください。

**Comment by Atria64** [comment]
大丈夫です！ありがとうございます！
